language: node_js

node_js:
  - 'node'
  - '10'
  - '8'
  - '7.10.1'

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
    node: '10'

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
